### ISSUE TITLE
PUT requests on subordinate resources should refresh the corresponding element

### ISSUE THREAD

**Issue by kaefer3000** [uvdsl/solid-inbox-watcher#5]
While PUT requests to update resources within the container trigger a notification that the inbox has been updated, the corresponding element in the HTML is not updated and continues to show the old data.

**Comment by kaefer3000** [comment]
If it's easy to add a flashy transition to the one who had been updated, that would be super cool!

**Comment by uvdsl** [comment]
Updating updated LDNs is adressed in  bea6e7ea6d4b7d95894ed6edd0d6899c494fcf8b.
However, in that commit, there sneaked some other changes in design in.

And you probably would want to make a clean install (remove node_modules and npm install) since I updated some libraries.
Sorry for the inconvenience.

The flashy update animation is a nice touch, will look into it :)

**Comment by uvdsl** [comment]
Flashy Update animation is adressed by 117b4d32ada88aac447603d29c394e859804a4b4.
It is also triggered when the LDN is loaded for the first time.

If you have any remarks, to this topic, please reopen this issue.
